### ISSUE TITLE
Add a Kyua quickstart guide

### ISSUE THREAD

**Issue by rodrigc** [freebsd/kyua#132]
I have talked to a few people, and they have all told me that the
documentation for kyua is oriented towards discussing how kyua was implemented,
and not so focused on quickly bootstrapping someone who wants to use kyua.

I wrote this quickstart guide to kyua:

https://github.com/rodrigc/kyuawiki2/commit/e4c9b1e5019d1c6f6b18a619e3a2bcce3e1c5611

I tried to keep it as minimal as possible.  I've gotten some positive feedback about it.
Please incorporate it into the main kyua wiki.

You can see the rendered form of the quickstart guide here:

https://github.com/rodrigc/kyua/wiki/Quickstart-Guide

**Comment by rodrigc** [comment]
@jmmv: can you incorporate this into the Kyua wiki docs?

**Comment by jmmv** [comment]
Oh yes. Last time I looked, I did not feel the guide was well-organized, but now it looks much better! Do you mind if I tweak the style and wording a bit when doing so?

**Comment by rodrigc** [comment]
Do what you have to do.  Let's get this in.

**Comment by rodrigc** [comment]
Can you accept this patch as it is, and then fixup the wiki to your requirements later?
I understand that you are busy with implementing parallel test execution, but I submitted this patch 5 months ago.  It would be good to get this in, to improve the docs.

**Comment by jmmv** [comment]
Let's do this now. I apologize again for the delays. I had separated my OSS email to a different account with the idea to look at it only when I had "free" time but the experiment has utterly failed... so I'm reverting that.

**Comment by jmmv** [comment]
Merged your Quickstart Installation contents into the regular Installation page. There shouldn't be two.

**Comment by jmmv** [comment]
Alright, I think I have imported everything. Let me know if I missed anything.

I have also wiped the front page of the wiki and reduced it to some links, and moved the contents to the sidebar for cleaner looks.

**Comment by rodrigc** [comment]
@jmmv: thanks for doing this.  I hear ya regarding _free_ time.  I don't think there is such a thing as _free_ time any more....:)

**Comment by jmmv** [comment]
Heh, indeed. Well, more than "free time" I was intending to treat Kyua as "work" and explicitly setting aside time for it either at home or in the office (20% time, etc. etc.). But because doing the latter is hard, I have been missing all project notifications... which is certainly not good for anyone.

Anyway: no, thank _you_ for writing this up and contributing it!
