### ISSUE TITLE
make check failures on FreeBSD

### ISSUE THREAD

**Issue by roman-neuhauser** [freebsd/kyua#134]
i get these two failures from `make check` in both 0.11 and current master (146b00df2c3d4b07e4b130672f19e07f3e651878), with atf and lutok installed using pkg(8)

```
model/metadata_test:override_all_with_set_string  ->  failed: Line 253: disk_space != md.required_disk_space() (16777216.00T != 2.00G)  [0.018s]

testers/tap_parser_test:try_parse_plan__insane  ->  failed: testers/tap_parser_test.c:135: 'too long' not matched in 'Plan line includes out of range numbers'  [0.011s]
```

**Comment by roman-neuhauser** [comment]
> seems like a low disk space condition or some kind

i can't bring myself to believe kyua tests want 16 _exabytes_ :)

**Comment by roman-neuhauser** [comment]
i've forgotten the machine in question is 32bit.

**Comment by ngie-eign** [comment]
That's the problem:

<pre>
$ sudo kyua test local/kyua/model/metadata_test:override_all_with_set_string
local/kyua/model/metadata_test:override_all_with_set_string  ->  passed  [0.011s]
Results file id is usr_tests.20141129-063106-135791
Results saved to /root/.kyua/store/results.usr_tests.20141129-063106-135791.db
1/1 passed (0 failed)
$ uname -a
FreeBSD fuji-current-amd64.local 11.0-CURRENT FreeBSD 11.0-CURRENT #3 r274552+aa10172(isilon-atf): Sat Nov 15 14:19:16 PST 2014     root@fuji-current-amd64.local:/usr/obj/usr/src/sys/FUJI-DEBUG  amd64
</pre>

<pre>
$ sudo kyua test local/kyua/model/metadata_test:override_all_with_set_string
local/kyua/model/metadata_test:override_all_with_set_string  ->  failed: Line 253: disk_space != md.required_disk_space() (16777216.00T != 2.00G)  [0.013s]
Results file id is usr_tests.20141129-063223-083967
Results saved to /root/.kyua/store/results.usr_tests.20141129-063223-083967.db
0/1 passed (1 failed)
$ uname -a
FreeBSD fuji-current-i386.local 11.0-CURRENT FreeBSD 11.0-CURRENT #12 r275110+74b69cf(isilon-atf): Wed Nov 26 17:44:14 PST 2014     ngie@fuji-current-i386.local:/usr/obj/usr/src/sys/FUJI  i386
</pre>

**Comment by jmmv** [comment]
With much more effort than I expected, I've added CI 32-bit builds to prevent this and other issues from recurring in 4c0839245c030a741bcf4014c8567d464e0ce47a.
