### ISSUE TITLE
SIGBUS on arm

### ISSUE THREAD

**Issue by bapt** [freebsd/kyua#137]
I'm trying to run pkg regression tests on arm, but kyua dies at startup with SIGBUS.

I do not have yet an stacktrace

**Comment by bapt** [comment]
Nevermind this is a freebsd bug on arm

**Comment by jmmv** [comment]
Out of curiosity, do you have a bug number?

I just got rid of the only ARM machine I had (a Raspberry PI), but I think this is a long-standing issue with C++ support. I think last time I tried months ago also showed this issue.

**Comment by bapt** [comment]
There is no ticket yet but a patch I have succesfully tested https://lists.freebsd.org/pipermail/freebsd-arm/2015-January/010014.html
