### ISSUE TITLE
atf_inttest.test_cleanup_crash failed to find necessary failure condition string

### ISSUE THREAD

**Issue by ngie-eign** [freebsd/kyua#140]
From https://jenkins.freebsd.org/job/FreeBSD_HEAD-tests/1053/testReport/junit/local.kyua.testers/atf_inttest/test__cleanup__crash/ :

<pre>
Error Message

testers/atf_inttest.c:207: atf_utils_compare_file("test-result", "broken: Test case cleanup received signal 6 (core dumped)\n") not met
Standard Output

subprocess stderr: About to die due to SIGABRT!
subprocess stderr: Subprocess timed out; sending KILL signal...
subprocess stderr: Process with PID 46776 dumped core; attempting to gather stack trace
subprocess stderr: (no debugging symbols found)...Core was generated by `atf_helpers'.
subprocess stderr: Program terminated with signal 6, Aborted.
subprocess stderr: (no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...#0  0x0000000800b7567a in thr_kill () from /lib/libc.so.7
subprocess stderr: GDB exited successfully
</pre>

**Comment by jmmv** [comment]
I'm going to close this as obsolete. All of the testers code has been removed so the problem above is either gone or has moved; a new release with all the hot shininess is due soon. (It's hard for me to tell if the bug is gone because I do not know what caused the issue...)
