### ISSUE TITLE
Improve error reporting for sqlite errors

### ISSUE THREAD

**Issue by emaste** [freebsd/kyua#141]
I happened to run kyua on an NFS root test box and it reports:

```
x220# kyua test
kyua: E: disk I/O error
```

It turns out this is because I didn't have lockd running.

Error messages like this ought to include information to help diagnose the issue -- for instance, reporting the file name and the operation that failed.

**Comment by jmmv** [comment]
Oh wow, that's surprising as the majority of the error handling tries to add some details to the operation that was being run. Of course, there may be corner cases where this is not being done.

How can I set things up to reproduce this? I'd need to track down where exactly this particular exception was raised so that the message can be fixed.

**Comment by ngie-eign** [comment]
> On Jun 28, 2015, at 20:17, Julio Merino notifications@github.com wrote:
> 
> Oh wow, that's surprising as the majority of the error handling tries to add some details to the operation that was being run. Of course, there may be corner cases where this is not being done.
> 
> How can I set things up to reproduce this? I'd need to track down where exactly this particular exception was raised so that the message can be fixed.
> 
> ―
> Reply to this email directly or view it on GitHub.
- Setup NFS
- Do not start lockd
- Mount NFS share over loopback
- Try to run kyua tests over NFS share; the data store should be on NFS

**Comment by jmmv** [comment]
Hmm... the only thing that uses locking is sqlite, so the problem ought to be coming from that end. That narrows the possibilities quite a bit.

**Comment by jmmv** [comment]
Simple code inspection shows plenty of places in the store module that rewrap sqlite errors without adding details to them. I'll target fixing those as part of this bug.

**Comment by emaste** [comment]
Thanks!
