### ISSUE TITLE
A number of atf-c-api "utility functions" are implemented but not documented

### ISSUE THREAD

**Issue by ngie-eign** [freebsd/kyua#150]
Examples from atf-c-api v0.20:

<pre>
     void
     atf_utils_cat_file(const char *file, const char *prefix);

     bool
     atf_utils_compare_file(const char *file, const char *contents);

     void
     atf_utils_copy_file(const char *source, const char *destination);

     void
     atf_utils_create_file(const char *file, const char *contents, ...);

     void
     atf_utils_file_exists(const char *file);

     pid_t
     atf_utils_fork(void);

     void
     atf_utils_free_charpp(char **argv);

     bool
     atf_utils_grep_file(const char *regexp, const char *file, ...);

     bool
     atf_utils_grep_string(const char *regexp, const char *str, ...);

     char *
     atf_utils_readline(int fd);

     void
     atf_utils_redirect(const int fd, const char *file);

     void
     atf_utils_wait(const pid_t pid, const int expected_exit_status,
         const char *expected_stdout, const char *expected_stderr);
</pre>

All that's mentioned are the function parameters, not the function behavior or function contracts.

**Comment by jmmv** [comment]
Could you please file this against the jmmv/atf tracker instead? (I'd do it myself... but then you lose ownership of the bug and not get replies to it.)

That said, all these should already be documented in the "Utility functions" section. The top of the page is just the SYNOPSIS without descriptions.
