### ISSUE TITLE
Switch to C++11

### ISSUE THREAD

**Issue by jmmv** [freebsd/kyua#152]
I think it's about time we permit the use of C++11.

A good reason for this is to modernize the codebase and gain code simplicity: range-based for loops and auto types are just so much better than typing iterators and complex types.

However, the real reason is to gain access to `std::thread`: the current subprocess-based executor model for parallelism is just too complex, and extending it to gain even more parallelism (think running test case listings independently) would make it insane to understand. The current model started as something relatively simple but, with the implementation of the ATF interface, became very hard to manage (try to see how cleanup routines are handled).

The specifics of this bug are to drop `utils/shared_ptr.hpp`, which will in turn require changes to the Travis configuration to install compilers that do support C++11 in our continuous builds (e.g. upgrade to GCC 4.8). Once that is done, we should be free to start using more interesting C++11 features.

Out of curiosity, I took a look at what Firefox does, which is a program that is widely available, and they do now accept C++11 as well.

**Comment by ngie-eign** [comment]
This is now a hard requirement via bf8eb104de96a1d80569b3d9ff3f2633c026c4f5.

**Comment by ngie-eign** [comment]
Addressed in commits noted above.
