### ISSUE TITLE
require.progs not supported by kyua(1)

### ISSUE THREAD

**Issue by ngie-eign** [freebsd/kyua#154]
atf-sh, etc allows specification of require.progs, but kyua(1) doesn't.

**Comment by jmmv** [comment]
Please provide more details on what you were running and with what versions of ATF and Kyua. There are extensive tests in Kyua to ensure the metadata is parsed properly so it is surprising to hear that `require.progs` does not work.

But just in case I did a manual spot-check and things do seem to work.

**Comment by jmmv** [comment]
Closing due to no reply. Please reopen if you can provide more data.
