### ISSUE TITLE
atf-sh examples from quickstart or man page are broken

### ISSUE THREAD

**Issue by bugaroo** [freebsd/kyua#157]
Plain tests and atf-c works fine, but when running `kyua test` with the atf-sh version it fails with this error:

```
atf_tests1.sh:__test_cases_list__ -> broken: Tester did not exit cleanly: kyua-atf-tester: Test program list did not return success [0.000s]
```

Instead of the list of tests, `kyua list` shows this:

```
atf_tests1.sh:__test_cases_list__
```

Both the atf_tests1.sh and the Kyuafile are exactly as shown in the quickstart guide. Also tried the example in atf-sh-api(3) but gets the exact same error.

This is on FreeBSD 10.3 with the kyua from ports.

**Comment by jmmv** [comment]
Did you grant executable permissions to the `atf_tests1.sh` script?

Does `/usr/local/bin/atf-sh` exist?

(I've fixed the documentation to clarify that the script must be executable, and I've also replaced the shebang with `/usr/bin/env atf-sh` for more reliability.)

**Comment by jmmv** [comment]
I'll consider this resolved due to the corresponding documentation fixes, which did not properly state the requirements of a shell test. Please try the new procedure and reopen this if it's still problematic.
