### ISSUE TITLE
configure.ac:65: error: Cannot find pkg.m4; see the INSTALL document for help

### ISSUE THREAD

**Issue by RajeshDasari** [freebsd/kyua#162]
While running "autoreconf -i -v -s -I /home/radasari/atf/home/radasari/rajesh/share/aclocal" command i was facing the below issue , 

autoreconf: running: aclocal -I /home/radasari/atf/home/radasari/rajesh/share/aclocal -I m4
configure.ac:65: error: Cannot find pkg.m4; see the INSTALL document for help
configure.ac:65: the top level
autom4te: /opt/m4/linux64/ix86/m4_1.4.17/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1

atf is installed in the path which i have provided , all the packages required by kyua are installed and I see that other packages like Lua and lutok compiled successfully with the same version of the automake and autoconf tools ,

I think this is not an issue in kyua and i missed something in the procedure , could someone please help me on this . 

pkg-config --version
0.21
autoconf --version
autoconf (GNU Autoconf) 2.69

 automake --version
automake (GNU automake) 1.15

**Comment by jmmv** [comment]
Does `pkg.m4` exist in `/home/radasari/atf/home/radasari/rajesh/share/aclocal`?

**Comment by RajeshDasari** [comment]
Hi ,
Thanks for your qucik response ,

Does pkg.m4 exist in /home/radasari/atf/home/radasari/rajesh/share/aclocal?
   No , pkg.m4 is not present in this directory .
 I have compiled the  with the same atf and other dependant package versions on a different machines , there autoreconf was successful  even there /atf/ home/radasari/rajesh/share/aclocal doesnt have pkg.m4 file .
In the machine where compilation was successful:
 m4 version :m4 (GNU M4) 1.4.17
 pkg-config --version : 0.28
In the machine where compilation failed with the reported error:
m4 version : m4 (GNU M4) 1.4.5
pkg-config --version : 0.21 

apart from those mentioned versions there was no difference .

**Comment by jmmv** [comment]
You have to tell `autoreconf` where all necessary `.m4` files are with `-I` flags. It's possible that on one of your systems `pkg.m4` is in a location not automatically scanned by the version of `autoreconf` you are using.

**Comment by RajeshDasari** [comment]
There seems to be an issue in my environment , Thanks a lot for your inputs .
