### ISSUE TITLE
Kyua fails to execute plain test program in expect (absolute path related)

### ISSUE THREAD

**Issue by dengio** [freebsd/kyua#163]
I'm trying to write a test for an interactive program using expect. The expect script by itself runs fine, and $? returns 0. However, when run from kyua the test fails.

The expect script spawns a program in the current directory and interacts with it. If the absolute path of the program is hardcoded into the expect script kyua successfully runs the test, otherwise it fails.

The line that causes the problem is `spawn [pwd]/myprogram` which, if printed, correctly resolves to the absolute location of the program being tested, and when run directly works as it should.

I've written other tests in sh that dynamically build the absolute path to the binary and they work fine. BTW, it would be nice if this was unnecessary, running `./myprogram` should just work.

A minimal test case is attached.

**Comment by ngie-eign** [comment]
@dengio could you please attach the test case?

**Comment by dengio** [comment]
This crappy website refuses my .zip file so I'll have to copy/paste by hand:

Kyuafile

```
syntax(2)
test_suite('bug')

plain_test_program{name='myecho_test.exp'}
```

Makefile

```
myecho: myecho.c
    cc $? -o $@
```

myecho.c

```
#include <stdio.h>

int main()
{
    int c;

    while((c = getchar()) != EOF)
        putchar(c);
}
```

myecho_test.exp

```
#! /usr/local/bin/expect -f

spawn [pwd]/myecho
sleep 1
send "hi\r"
expect "hi\r"
send \004
expect eof
```

**Comment by jmmv** [comment]
This is working as intended. Test programs are executed in a temporary directory in an attempt to isolate them from the rest of the system. In particular, this allows test programs to freely create test files under the current directory, allowing Kyua to automatically clean them up on exit.

You'll have to provide the absolute path to the helper files for your test, which you should determine based on the location of the test program. `$(dirname "${0}")` would do the trick for a shell script.

See _Test isolation_ under `kyua-test(1)` for more details on this and other relevant topics.

**Comment by dengio** [comment]
The absolute path is being provided, that's the issue. It works for shell scripts but not for expect scripts, I tought plain tests were supposed to be language agnostic.

`[pwd]` is the expect equivalent of `$(dirname "${0}")`

**Comment by jmmv** [comment]
`[pwd]` (https://www.tcl.tk/man/tcl/TclCmd/pwd.htm) returns the path to the _current working directory_ whereas `$(dirname "${0}")` returns the path to the script being run (as given by the user). These are not equivalent.

When Kyua runs your test, it first changes the current work directory to a temporary directory and then invokes your expect script. As a result, the expect script's current working directory is _not_ the same as where the script is originally located.

You will have to provide an absolute path, either hardcoding it (suboptimal) or dynamically determining it from the location of the running expect script.

**Comment by dengio** [comment]
Now it's all very clear. Replacing `[pwd]` with either `[file dirname $argv0]` or `[file dirname [info script]]`in the expect script seems to work.
