### ISSUE TITLE
Suspending laptop/VM while test is running and resuming after test was supposed to be completed causes a failure; timers are setup incorrectly

### ISSUE THREAD

**Issue by ngie-eign** [freebsd/kyua#164]
If I have a test that runs for 30 seconds, suspend my laptop or VM for a minute, then resume it, the testcase will have failed.

I believe the issue is that the timer used with setitimer in utils/signals/timer.cpp is `ITIMER_REAL`, not `ITIMER_VIRTUAL`.

**Comment by ngie-eign** [comment]
This may also be manifested via ntpd forcing a clock to step forward, busy system timers (e.g. dtrace tests blocking things from making progress), etc.

**Comment by ngie-eign** [comment]
*sigh* CLOCK_MONOTONIC was what I was looking for, but that analog doesn't exist with setitimer :/.

**Comment by ngie-eign** [comment]
Ok, I found out the real way forward -- setitimer needs to be replaced with timer_create (POSIX compliant way for setting timers..): https://linux.die.net/man/2/timer_create

**Comment by jmmv** [comment]
This is essentially https://github.com/jmmv/kyua/issues/155, I think. See my last reply there; I'm not sure that makes sense.

**Comment by ngie-eign** [comment]
Yeah... #155 looks like a winner.
