### ISSUE TITLE
can't configure kyua on CentOS 7 even after installing lutok-3

### ISSUE THREAD

**Issue by TimFH** [freebsd/kyua#168]
./configure exits with

configure: error: lutok (0.4 or newer) is required

but "ls /usr/local/lib" shows

liblua.a             liblutok.so.3               liblutok.a           liblutok.so.3.0.0

were installed correctly. Anyone know why?

**Comment by TimFH** [comment]
The "liblutok.so.3.0.0" label persists even after installing from a lutok-0.4 tarbar. Moving it to "liblutok.4.0.0" didn't help.

**Comment by jmmv** [comment]
Shared library version numbers represent the ABI, not the package name. It's fine for `liblutok.so` to be at version "3" even when you have lutok 0.4.

What does `config.log` say about this failure?

This is probably pkg-config not finding the library. Do you need to set `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig` before calling `configure`?

**Comment by TimFH** [comment]
The relevant portion of config.log seems to be

configure:7366: gcc -E  conftest.c
conftest.c:11:28: fatal error: ac_nonexistent.h: No such file or directory
 #include <ac_nonexistent.h>
                            ^
compilation terminated.
configure:7366: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Lutok"
| #define PACKAGE_TARNAME "lutok"
| #define PACKAGE_VERSION "0.4"
| #define PACKAGE_STRING "Lutok 0.4"
| #define PACKAGE_BUGREPORT "lutok-discuss@googlegroups.com"
| #define PACKAGE_URL "http://code.google.com/p/lutok/"
| #define PACKAGE "lutok"
| #define VERSION "0.4"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:7391: result: gcc -E
configure:7411: gcc -E  conftest.c
configure:7411: $? = 0
configure:7425: gcc -E  conftest.c
conftest.c:11:28: fatal error: ac_nonexistent.h: No such file or directory
 #include <ac_nonexistent.h>
                            ^
compilation terminated.

Putting the PKG_CONFIG_PATH=/usr/local/lib/pkgconfig however fixed the problem!

Thank you very much.
