### ISSUE TITLE
feature request: 'debug' for multiple files.

### ISSUE THREAD

**Issue by trasz** [freebsd/kyua#180]
It would be great if we could use "debug" as a drop-in replacement for "test", to make it run multiple cases (like, the whole test suite).  This way, when run from eg. Jenkins, we would have useful info, like backtraces, immediately when looking at the log.

**Comment by jmmv** [comment]
`debug` for multiple tests doesn't make sense as it is specifically designed to change the way an individual test gets run.

What you are asking for, I guess, is for `test` to print failure details for any failed tests, without having to run a separate `report` step. But you can trivially get this by doing `kyua test || kyua report --verbose`.

However, if you are running Kyua from Jenkins, you should really generate a Junit report with `report-junit` and configure Jenkins to look for this. This would give you structured logs from the UI for any failures.
